# Generated by Django 3.2.5 on 2021-07-10 22:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=15, unique=True)),
                ('gener', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('active', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('document_type_id', models.ForeignKey(blank=True, db_column='document_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.documenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
