# Generated by Django 3.2.5 on 2021-07-11 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_cab_vehicle'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'cancel'), (1, 'waiting'), (2, 'accepted')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cab_id', models.ForeignKey(db_column='cab_id', on_delete=django.db.models.deletion.PROTECT, to='drivers.cab')),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('state', models.IntegerField(choices=[(1, 'Paused'), (2, 'Active'), (3, 'Finished')])),
                ('request_id', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.PROTECT, to='trips.requesttrip')),
            ],
        ),
    ]
