# Generated by Django 3.2.5 on 2021-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttrip',
            name='state',
            field=models.IntegerField(choices=[(0, 'Cancel'), (1, 'Waiting'), (2, 'Accepted')], default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
