# Generated by Django 3.2.5 on 2021-07-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=8)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('base_amount', models.FloatField()),
                ('trip_id', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.PROTECT, to='trips.trip')),
            ],
        ),
    ]
