# Generated by Django 3.2.5 on 2021-07-12 00:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point([0, 0]), srid=4326),
        ),
    ]
